version: 2

sources: 
  - name: staging
    database: trans-mind-429208-g1
    schema: ny_taxi
    tables:
      - name: green_cab_data
      - name: yellow_cab_data
         # freshness:
           # error_after: {count: 6, period: hour}
    